export const propertiesData = [
    {
        id: 1,
        image: [
            'https://picsum.photos/250/350?random=1',
            'https://picsum.photos/250/350?random=2',
            'https://picsum.photos/250/350?random=3',
            'https://picsum.photos/250/350?random=4',
            'https://picsum.photos/250/350?random=5',
        ],
        capa: 'https://picsum.photos/250/350',
        description: 'Descrição do imovel',
        title: 'Apartamento na Praia',
        area: 80,
        price: '350.000,00',
        level: 'Intermediário',
        brique: 'Venda',
        tipo: 'Apartamento',
        destaque: true
    },
    {
        id: 2,
        image: [
            'https://picsum.photos/250/350?random=1',
            'https://picsum.photos/250/350?random=2',
            'https://picsum.photos/250/350?random=3',
            'https://picsum.photos/250/350?random=4',
            'https://picsum.photos/250/350?random=5',
        ],
        capa: 'https://picsum.photos/250/350',
        description: 'Descrição do imovel',
        title: 'Casa no Campo',
        area: 120,
        price: '500.000,00',
        level: 'Alto Padrão',
        brique: 'Venda',
        tipo: 'Apartamento',
        destaque: false
    },
    {
        id: 3,
        image: [
            'https://picsum.photos/250/350?random=1',
            'https://picsum.photos/250/350?random=2',
            'https://picsum.photos/250/350?random=3',
            'https://picsum.photos/250/350?random=4',
            'https://picsum.photos/250/350?random=5',
        ],
        capa: 'https://picsum.photos/250/350',
        description: 'Descrição do imovel',
        title: 'Cobertura Duplex',
        area: 200,
        price: '1.200.000,00',
        level: 'Alto Padrão',
        brique: 'Venda',
        tipo: 'Apartamento',
        destaque: true
    },
    {
        id: 4,
        image: [
            'https://picsum.photos/250/350?random=1',
            'https://picsum.photos/250/350?random=2',
            'https://picsum.photos/250/350?random=3',
            'https://picsum.photos/250/350?random=4',
            'https://picsum.photos/250/350?random=5',
        ],
        capa: 'https://picsum.photos/250/350',
        description: 'Descrição do imovel',
        title: 'Apartamento Compacto',
        area: 50,
        price: '250.000,00',
        level: 'Intermediário',
        brique: 'Aluguel',
        tipo: 'Casa',
        destaque: false
    },
    {
        id: 5,
        image: [
            'https://picsum.photos/250/350?random=1',
            'https://picsum.photos/250/350?random=2',
            'https://picsum.photos/250/350?random=3',
            'https://picsum.photos/250/350?random=4',
            'https://picsum.photos/250/350?random=5',
        ],
        capa: 'https://picsum.photos/250/350',
        description: 'Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.',
        title: 'Casa de Praia',
        area: 150,
        price: '800.000,00',
        level: 'Alto Padrão',
        brique: 'Aluguel',
        tipo: 'Fazenda',
        destaque: true
    },
];